# Generated by Django 5.0.2 on 2024-06-22 18:16

import django.db.models.deletion
import tenant.mother
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='Kumasi', max_length=60)),
                ('school_name', models.CharField(blank=True, default='KNUST', max_length=60)),
                ('email', models.EmailField(blank=True, default='knust@gmail.com', max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_plain', models.CharField(default='zTSgthecZixPHdKGAkyQlRvJaL', max_length=60)),
                ('key_encrypted', models.CharField(default='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmnVyVCoFwxg0Wvtf39iYIS9XsYb4cG25X5mj1JZUWu8GTC1J3VOJXU69OwAP2qaag0E6vKAiCa6je0UvvlIxwpWdKwSo1C3YgxeX9zC2zeixTO9Xwg+LG8CK9ru7y/Pe9owL+5Hw9fSf2rd0DSEi12OZ82GyNQ2u18bLbtHZY4JTNenfNcgX910M+6zRy+eCPPATvYypmZ6jskUMZouwWuGOWpEOWAW1omqxmRZQA6hMWxZk/leldXCCt06Oj4CQq3TKa5BQax6Y7VND+jPjFDqXxETPm3LXbo76OEabDQ9jk2Frdn22p75jx4rxGu0NcNF+ETBIMPbVeNVj+0awtQIDAQAB', max_length=2048)),
                ('date_proc', models.DateTimeField()),
                ('date_exp', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default=tenant.mother.Key.check_status, max_length=12)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.school')),
            ],
        ),
    ]
