# Generated by Django 5.0.2 on 2024-06-24 23:31

import datetime
import django.utils.timezone
import tenant.mother
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='date_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 23, 31, 2, 624239, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='date_proc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_encrypted',
            field=models.CharField(default='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApl4aLd4E7TIrgJTU+lVtUhYFlxEq6qojaaTwriFYfFzUQ71jOwW2VNnDnl5PdoFKe9uHwNv8tCvcZHeBRLzPQZ8e0V3/By+55wrRI4BpNgSaDsWp7QYI3ed0kp8dkS8vwiyxerdK28BiPLyoVpkiYLVuV/UBFiYyfMngO2lw2pmJshYtUuq5YECQ51xSa70j+ERGFUaiD5aSf0tV3pKqLBeqsrvwZg8piYnzitn6/aAHvuiqkfw8lZJCSDKKkV8x2u2WBqkqxV/w3ZZ4IpZu0+M7m+KV+wI1iGMDXIsgzhJ8woltHDOV3I6HAt+TxtMNPSB6r2/fgre7hwi8oNH1AQIDAQAB', max_length=2048),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_plain',
            field=models.CharField(default='xdvNZlmUJKyIFLYaWHzueqQn', max_length=60),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default=tenant.mother.Key.check_status, max_length=12),
        ),
    ]
