# Generated by Django 5.0.2 on 2024-06-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, default='knust@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, default='KNUST', max_length=60),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, default='Kumasi', max_length=60),
        ),
    ]
