# Generated by Django 5.0.2 on 2024-06-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_remove_school_user_school_email_school_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key_encrypted',
            field=models.CharField(default='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxpXaNjBaz1t3HT3p9QWRBWO5GzDadyu0fAqXjZn9gKTv36PTcWOaiutoEeMyLurERVnxjL7uJvl2qyge+zNakqVtMhmhBEbmy/g0EaGcR0Kq1Gmlsa9vUM90t1V74wR06xGiJdZ1lPdeHIy8Gd8wLBsHbAHL7PancRoe7Pl1RMC+4M/Hnc0n15B5m5oOG/lZDOb0lbDHBpQpKBHKG/xUG9kam6lydCaENAOVXKcbKRZ/Tbj66TAwERIsA/9FTWvtRdI00tzm088dLcXTCmdDdZCcNNhtJpyNaERhkZfx8zrArU+yqyem3FSjY9OnDm9OUNHP9XxRQsmRwrI8fqMnTwIDAQAB', max_length=2048),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_plain',
            field=models.CharField(default='AbzfGaIUnvrwRMxljg', max_length=60),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='Active', max_length=12),
        ),
    ]
