# Generated by Django 5.0.2 on 2024-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_accesskey_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key_encrypted',
            field=models.CharField(default='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp07Tr2VLnnRiv+XY8CLyRtatBx051croJ2MMlAAsdIqvTByNgUnjrD4wWA4qgZQTfUVElfGl0OM28ZKvZBkbEy82roHHo2TuRlMiNlespHgICtLhLsE2fv5jgLLq916jS6ImOb/tZaGEGjZdPliO/yZfrJf9M97BLNLQq+LwsoYLfBE9PDxm5k/YaWlj7Y1qRNkAZpSFmr3USCtRuivfdiDR9cCPt3Hq8A27AHDyQvMzLgfjltlofccF3XFKBzQvG9sNhBT+RpK7MO5QEpSdres7BRT3YErdq/uh7+IHNpE1ren4p1TBPY70Y+nsJI4B0IKTYwXWsdcXbQxiXOcLMQIDAQAB', max_length=2048),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_plain',
            field=models.CharField(default='FbamkpVoM', max_length=60),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='Revoked', max_length=12),
        ),
    ]
